[project]
name = "japan-ai-cup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hydra-core>=1.3.2",
    "lightgbm>=4.6.0",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
]
